- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        ec2_region: us-east-2
        state: 'absent'
        instance_ids: 'i-0c1ba30adffe43322'
